// src/types/firestore.ts
import { Timestamp } from 'firebase/firestore';

// 1. USERS COLLECTION ('users')
export interface UserDocument {
  uid: string;
  email: string;
  displayName: string;
  photoURL?: string;
  studioName?: string;
  role?: string;
  accessStatus: 'waitlist' | 'approved' | 'admin';
  createdAt: Timestamp;
}

// 2. PROJECTS COLLECTION ('projects')
export interface ProjectDocument {
  id: string;         // Auto-generated by Firestore
  ownerId: string;    // Links to users/{uid}
  title: string;
  status: 'draft' | 'completed';
  lastModified: Timestamp;
  
  // The core content (The "Current State")
  data: {
    logline: string;
    synopsis?: {
      intro: string;
      plot: string;
      resolution: string;
    };
    // We store modules as arrays of objects here
    modules?: {
      characters: Array<{ id: string; name: string; tag: string; color: string }>;
      settings: Array<{ id: string; name: string; tag: string; color: string }>;
      themes: Array<{ id: string; name: string; tag: string; color: string }>;
    };
  }
}

// 3. VERSIONS SUB-COLLECTION ('projects/{projectId}/versions')
// Path example: db.collection('projects').doc('project_123').collection('versions').add(...)
export interface VersionDocument {
  id: string;
  timestamp: Timestamp;
  label: string;      // e.g., "Logline Draft 1"
  phase: 'logline' | 'synopsis';
  snapshotData: ProjectDocument['data']; // A copy of the data at that moment
}